### PR TITLE
test PR to test Action

### PR DESCRIPTION
**Pull request by hamelsmu**
cc: @Aylr I wasn't able to reproduce error.  I have added a matrix build to test all permutations of possible input checkpoints.   Let's see what happens on this PR.   ref: #71 

(If it doesn't work this will be embarassing)

### CODE REVIEW

**Comment by hamelsmu** [comment]
ok its not really 100% the commenting is a messed up but I can fix that

**Comment by hamelsmu** [comment]
ok trying it again

**Comment by Aylr** [comment]
This all makes sense to me. I wonder what I was doing wrong.

**Pull request closed without merging**
